<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>OTHL - Pro Standing</title>
<script src="OTHL.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Tyler Bell - STHS - Version : 3.1.6.6" />
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1060px) {
.STHSWarning {display:block;}
table.basictablesorter thead th:nth-last-child(3){display:none;}
table.basictablesorter tbody td:nth-last-child(3){display:none;}
table.basictablesorter thead th:nth-last-child(4){display:none;}
table.basictablesorter tbody td:nth-last-child(4){display:none;}
table.basictablesorter thead th:nth-last-child(5){display:none;}
table.basictablesorter tbody td:nth-last-child(5){display:none;}
}@media screen and (max-width: 890px) {
table.basictablesorter thead th:nth-last-child(6){display:none;}
table.basictablesorter tbody td:nth-last-child(6){display:none;}
table.basictablesorter thead th:nth-last-child(7){display:none;}
table.basictablesorter tbody td:nth-last-child(7){display:none;}
}
table.basictablesorter tbody td.staticTD {font-size:9pt;border-right:hidden; border-left:hidden;}
</style>
<link href="OTHL.css" rel="stylesheet" type="text/css" />
<?php If (file_exists("STHSMain-CSSOverwrite.css") == true){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
</head><body>
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"OTHL-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"OTHL-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter({ widgets: ['staticRow'] })});</script>
<div class="tabsmain standard"><ul class="tabmain-links">
<li class="activemain"><a href="#tabmain1">Wildcard</a></li>
<li><a href="#tabmain2">Conference</a></li>
<li><a href="#tabmain3">Division</a></li>
<li><a href="#tabmain4">Overall</a></li>
</ul><div class="tabmain-content">
<div class="tabmain active" id="tabmain1">
<h2 class="STHSStanding_H2Header">Eastern Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr class="static"><td  class="staticTD"></td><td class="staticTD"><b>Adams Division</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 A</td><td><a href="OTHL-ProTeamRoster.php#Canadiens">Canadiens</a></td><td>7</td><td>5</td><td>0</td><td>2</td><td><b>12</b></td><td>4</td><td>23</td><td>18</td><td>5</td><td>0.857</td><td>2-0-2</td><td>3-0-0</td><td>5-0-2</td><td>2-0-2</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>2 A</td><td><a href="OTHL-ProTeamRoster.php#Panthers">Panthers</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>18</td><td>4</td><td>0.786</td><td>3-0-0</td><td>2-1-1</td><td>5-1-1</td><td>3-0-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>3 A</td><td><a href="OTHL-ProTeamRoster.php#Sabres">Sabres</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>4</td><td>23</td><td>15</td><td>8</td><td>0.625</td><td>1-1-2</td><td>3-1-0</td><td>4-2-2</td><td>1-1-2</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr class="static"><td  class="staticTD"></td><td class="staticTD"><b>Patrick Division</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 P</td><td><a href="OTHL-ProTeamRoster.php#Islanders">Islanders</a></td><td>7</td><td>7</td><td>0</td><td>0</td><td><b>14</b></td><td>6</td><td>24</td><td>11</td><td>13</td><td>1.000</td><td>5-0-0</td><td>2-0-0</td><td>7-0-0</td><td>5-0-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>2 P</td><td><a href="OTHL-ProTeamRoster.php#Capitals">Capitals</a></td><td>9</td><td>5</td><td>3</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>21</td><td>1</td><td>0.611</td><td>3-1-1</td><td>2-2-0</td><td>5-3-1</td><td>3-1-1</td><td>2-2-0</td><td>L1</td><td></td></tr>
<tr><td>3 P</td><td><a href="OTHL-ProTeamRoster.php#Devils">Devils</a></td><td>7</td><td>4</td><td>3</td><td>0</td><td><b>8</b></td><td>4</td><td>21</td><td>19</td><td>2</td><td>0.571</td><td>2-2-0</td><td>2-1-0</td><td>4-3-0</td><td>2-2-0</td><td>2-1-0</td><td>L1</td><td></td></tr>
<tr class="static"><td class="staticTD"></td><td class="staticTD"><b>Wildcard</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 A</td><td><a href="OTHL-ProTeamRoster.php#RedWings">Red Wings</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>2</td><td>24</td><td>24</td><td>0</td><td>0.625</td><td>3-0-0</td><td>1-2-2</td><td>4-2-2</td><td>3-0-0</td><td>1-2-2</td><td>SOW1</td><td></td></tr>
<tr><td>2 A</td><td><a href="OTHL-ProTeamRoster.php#Bruins">Bruins</a></td><td>7</td><td>4</td><td>2</td><td>1</td><td><b>9</b></td><td>2</td><td>20</td><td>20</td><td>0</td><td>0.643</td><td>2-1-0</td><td>2-1-1</td><td>4-2-1</td><td>2-1-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>3 A</td><td><a href="OTHL-ProTeamRoster.php#Senators">Senators</a></td><td>6</td><td>4</td><td>2</td><td>0</td><td><b>8</b></td><td>4</td><td>13</td><td>11</td><td>2</td><td>0.667</td><td>4-0-0</td><td>0-2-0</td><td>4-2-0</td><td>4-0-0</td><td>0-2-0</td><td>L1</td><td>1</td></tr>
<tr><td>4 P</td><td><a href="OTHL-ProTeamRoster.php#BlueJackets">Blue Jackets</a></td><td>7</td><td>3</td><td>3</td><td>1</td><td><b>7</b></td><td>3</td><td>18</td><td>24</td><td>-6</td><td>0.500</td><td>1-3-0</td><td>2-0-1</td><td>3-3-1</td><td>1-3-0</td><td>2-0-1</td><td>W2</td><td>2</td></tr>
<tr><td>5 P</td><td><a href="OTHL-ProTeamRoster.php#Rangers">Rangers</a></td><td>5</td><td>3</td><td>2</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0.600</td><td>1-1-0</td><td>2-1-0</td><td>3-2-0</td><td>1-1-0</td><td>2-1-0</td><td>W2</td><td>3</td></tr>
<tr><td>6 A</td><td><a href="OTHL-ProTeamRoster.php#Lightning">Lightning</a></td><td>7</td><td>3</td><td>4</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>20</td><td>-2</td><td>0.429</td><td>0-1-0</td><td>3-3-0</td><td>3-4-0</td><td>0-1-0</td><td>3-3-0</td><td>L1</td><td>3</td></tr>
<tr><td>7 A</td><td><a href="OTHL-ProTeamRoster.php#MapleLeafs">Maple Leafs</a></td><td>8</td><td>2</td><td>6</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>23</td><td>-7</td><td>0.250</td><td>1-4-0</td><td>1-2-0</td><td>2-6-0</td><td>1-4-0</td><td>1-2-0</td><td>L6</td><td>5</td></tr>
<tr><td>8 P</td><td><a href="OTHL-ProTeamRoster.php#Hurricanes">Hurricanes</a></td><td>9</td><td>1</td><td>7</td><td>1</td><td><b>3</b></td><td>1</td><td>18</td><td>34</td><td>-16</td><td>0.167</td><td>1-2-1</td><td>0-5-0</td><td>1-7-1</td><td>1-2-1</td><td>0-5-0</td><td>L3</td><td>6</td></tr>
<tr><td>9 P</td><td><a href="OTHL-ProTeamRoster.php#Flyers">Flyers</a></td><td>5</td><td>1</td><td>4</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>15</td><td>-7</td><td>0.200</td><td>1-1-0</td><td>0-3-0</td><td>1-4-0</td><td>1-1-0</td><td>0-3-0</td><td>L3</td><td>7</td></tr>
<tr><td>10 P</td><td><a href="OTHL-ProTeamRoster.php#Penguins">Penguins</a></td><td>8</td><td>1</td><td>7</td><td>0</td><td><b>2</b></td><td>1</td><td>18</td><td>30</td><td>-12</td><td>0.125</td><td>1-5-0</td><td>0-2-0</td><td>1-7-0</td><td>1-5-0</td><td>0-2-0</td><td>L1</td><td>7</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Western Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr class="static"><td  class="staticTD"></td><td class="staticTD"><b>Norris Division</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 N</td><td><a href="OTHL-ProTeamRoster.php#Jets">Jets</a></td><td>9</td><td>6</td><td>3</td><td>0</td><td><b>12</b></td><td>6</td><td>32</td><td>24</td><td>8</td><td>0.667</td><td>3-1-0</td><td>3-2-0</td><td>6-3-0</td><td>3-1-0</td><td>3-2-0</td><td>L1</td><td></td></tr>
<tr><td>2 N</td><td><a href="OTHL-ProTeamRoster.php#Predators">Predators</a></td><td>7</td><td>5</td><td>2</td><td>0</td><td><b>10</b></td><td>4</td><td>18</td><td>15</td><td>3</td><td>0.714</td><td>3-1-0</td><td>2-1-0</td><td>5-2-0</td><td>3-1-0</td><td>2-1-0</td><td>L1</td><td></td></tr>
<tr><td>3 N</td><td><a href="OTHL-ProTeamRoster.php#Blues">Blues</a></td><td>7</td><td>2</td><td>3</td><td>2</td><td><b>6</b></td><td>1</td><td>20</td><td>26</td><td>-6</td><td>0.429</td><td>0-1-2</td><td>2-2-0</td><td>2-3-2</td><td>0-1-2</td><td>2-2-0</td><td>L2</td><td></td></tr>
<tr class="static"><td  class="staticTD"></td><td class="staticTD"><b>Smythe Division</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 S</td><td><a href="OTHL-ProTeamRoster.php#Flames">Flames</a></td><td>8</td><td>7</td><td>1</td><td>0</td><td><b>14</b></td><td>6</td><td>27</td><td>12</td><td>15</td><td>0.875</td><td>3-1-0</td><td>4-0-0</td><td>7-1-0</td><td>3-1-0</td><td>4-0-0</td><td>W2</td><td></td></tr>
<tr><td>2 S</td><td><a href="OTHL-ProTeamRoster.php#Canucks">Canucks</a></td><td>6</td><td>6</td><td>0</td><td>0</td><td><b>12</b></td><td>4</td><td>23</td><td>12</td><td>11</td><td>1.000</td><td>3-0-0</td><td>3-0-0</td><td>6-0-0</td><td>3-0-0</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>3 S</td><td><a href="OTHL-ProTeamRoster.php#Ducks">Ducks</a></td><td>8</td><td>5</td><td>1</td><td>2</td><td><b>12</b></td><td>5</td><td>27</td><td>24</td><td>3</td><td>0.750</td><td>3-1-0</td><td>2-0-2</td><td>5-1-2</td><td>3-1-0</td><td>2-0-2</td><td>W2</td><td></td></tr>
<tr class="static"><td class="staticTD"></td><td class="staticTD"><b>Wildcard</b></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td><td class="staticTD"></td></tr>
<tr><td>1 S</td><td><a href="OTHL-ProTeamRoster.php#Sharks">Sharks</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>24</td><td>14</td><td>10</td><td>0.786</td><td>2-0-1</td><td>3-1-0</td><td>5-1-1</td><td>2-0-1</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>2 S</td><td><a href="OTHL-ProTeamRoster.php#Oilers">Oilers</a></td><td>8</td><td>3</td><td>2</td><td>3</td><td><b>9</b></td><td>3</td><td>22</td><td>21</td><td>1</td><td>0.563</td><td>2-0-2</td><td>1-2-1</td><td>3-2-3</td><td>2-0-2</td><td>1-2-1</td><td>SOL1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>3 S</td><td><a href="OTHL-ProTeamRoster.php#Coyotes">Coyotes</a></td><td>6</td><td>3</td><td>2</td><td>1</td><td><b>7</b></td><td>3</td><td>21</td><td>18</td><td>3</td><td>0.583</td><td>1-1-1</td><td>2-1-0</td><td>3-2-1</td><td>1-1-1</td><td>2-1-0</td><td>W1</td><td>2</td></tr>
<tr><td>4 S</td><td><a href="OTHL-ProTeamRoster.php#GoldenKnights">Golden Knights</a></td><td>8</td><td>3</td><td>4</td><td>1</td><td><b>7</b></td><td>3</td><td>17</td><td>24</td><td>-7</td><td>0.438</td><td>2-3-0</td><td>1-1-1</td><td>3-4-1</td><td>2-3-0</td><td>1-1-1</td><td>W1</td><td>2</td></tr>
<tr><td>5 N</td><td><a href="OTHL-ProTeamRoster.php#Stars">Stars</a></td><td>9</td><td>3</td><td>6</td><td>0</td><td><b>6</b></td><td>2</td><td>25</td><td>30</td><td>-5</td><td>0.333</td><td>1-2-0</td><td>2-4-0</td><td>3-6-0</td><td>1-2-0</td><td>2-4-0</td><td>W1</td><td>3</td></tr>
<tr><td>6 N</td><td><a href="OTHL-ProTeamRoster.php#Wild">Wild</a></td><td>7</td><td>2</td><td>4</td><td>1</td><td><b>5</b></td><td>2</td><td>16</td><td>18</td><td>-2</td><td>0.357</td><td>1-0-0</td><td>1-4-1</td><td>2-4-1</td><td>1-0-0</td><td>1-4-1</td><td>L1</td><td>4</td></tr>
<tr><td>7 N</td><td><a href="OTHL-ProTeamRoster.php#Blackhawks">Blackhawks</a></td><td>5</td><td>2</td><td>3</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>15</td><td>-3</td><td>0.400</td><td>1-3-0</td><td>1-0-0</td><td>2-3-0</td><td>1-3-0</td><td>1-0-0</td><td>L2</td><td>5</td></tr>
<tr><td>8 S</td><td><a href="OTHL-ProTeamRoster.php#Kings">Kings</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>23</td><td>-8</td><td>0.286</td><td>2-2-0</td><td>0-3-0</td><td>2-5-0</td><td>2-2-0</td><td>0-3-0</td><td>L1</td><td>5</td></tr>
<tr><td>9 N</td><td><a href="OTHL-ProTeamRoster.php#Avalanche">Avalanche</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>21</td><td>-10</td><td>0.286</td><td>1-3-0</td><td>1-2-0</td><td>2-5-0</td><td>1-3-0</td><td>1-2-0</td><td>L2</td><td>5</td></tr>
</tbody></table>
</div>
<div class="tabmain" id="tabmain2">
<h2 class="STHSStanding_H2Header">Eastern Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Islanders">Islanders</a></td><td>7</td><td>7</td><td>0</td><td>0</td><td><b>14</b></td><td>6</td><td>24</td><td>11</td><td>13</td><td>1.000</td><td>5-0-0</td><td>2-0-0</td><td>7-0-0</td><td>5-0-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Canadiens">Canadiens</a></td><td>7</td><td>5</td><td>0</td><td>2</td><td><b>12</b></td><td>4</td><td>23</td><td>18</td><td>5</td><td>0.857</td><td>2-0-2</td><td>3-0-0</td><td>5-0-2</td><td>2-0-2</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Panthers">Panthers</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>18</td><td>4</td><td>0.786</td><td>3-0-0</td><td>2-1-1</td><td>5-1-1</td><td>3-0-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#Capitals">Capitals</a></td><td>9</td><td>5</td><td>3</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>21</td><td>1</td><td>0.611</td><td>3-1-1</td><td>2-2-0</td><td>5-3-1</td><td>3-1-1</td><td>2-2-0</td><td>L1</td><td></td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Sabres">Sabres</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>4</td><td>23</td><td>15</td><td>8</td><td>0.625</td><td>1-1-2</td><td>3-1-0</td><td>4-2-2</td><td>1-1-2</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Devils">Devils</a></td><td>7</td><td>4</td><td>3</td><td>0</td><td><b>8</b></td><td>4</td><td>21</td><td>19</td><td>2</td><td>0.571</td><td>2-2-0</td><td>2-1-0</td><td>4-3-0</td><td>2-2-0</td><td>2-1-0</td><td>L1</td><td>1</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#RedWings">Red Wings</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>2</td><td>24</td><td>24</td><td>0</td><td>0.625</td><td>3-0-0</td><td>1-2-2</td><td>4-2-2</td><td>3-0-0</td><td>1-2-2</td><td>SOW1</td><td></td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#Bruins">Bruins</a></td><td>7</td><td>4</td><td>2</td><td>1</td><td><b>9</b></td><td>2</td><td>20</td><td>20</td><td>0</td><td>0.643</td><td>2-1-0</td><td>2-1-1</td><td>4-2-1</td><td>2-1-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>9</td><td><a href="OTHL-ProTeamRoster.php#Senators">Senators</a></td><td>6</td><td>4</td><td>2</td><td>0</td><td><b>8</b></td><td>4</td><td>13</td><td>11</td><td>2</td><td>0.667</td><td>4-0-0</td><td>0-2-0</td><td>4-2-0</td><td>4-0-0</td><td>0-2-0</td><td>L1</td><td>1</td></tr>
<tr><td>10</td><td><a href="OTHL-ProTeamRoster.php#BlueJackets">Blue Jackets</a></td><td>7</td><td>3</td><td>3</td><td>1</td><td><b>7</b></td><td>3</td><td>18</td><td>24</td><td>-6</td><td>0.500</td><td>1-3-0</td><td>2-0-1</td><td>3-3-1</td><td>1-3-0</td><td>2-0-1</td><td>W2</td><td>2</td></tr>
<tr><td>11</td><td><a href="OTHL-ProTeamRoster.php#Rangers">Rangers</a></td><td>5</td><td>3</td><td>2</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0.600</td><td>1-1-0</td><td>2-1-0</td><td>3-2-0</td><td>1-1-0</td><td>2-1-0</td><td>W2</td><td>3</td></tr>
<tr><td>12</td><td><a href="OTHL-ProTeamRoster.php#Lightning">Lightning</a></td><td>7</td><td>3</td><td>4</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>20</td><td>-2</td><td>0.429</td><td>0-1-0</td><td>3-3-0</td><td>3-4-0</td><td>0-1-0</td><td>3-3-0</td><td>L1</td><td>3</td></tr>
<tr><td>13</td><td><a href="OTHL-ProTeamRoster.php#MapleLeafs">Maple Leafs</a></td><td>8</td><td>2</td><td>6</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>23</td><td>-7</td><td>0.250</td><td>1-4-0</td><td>1-2-0</td><td>2-6-0</td><td>1-4-0</td><td>1-2-0</td><td>L6</td><td>5</td></tr>
<tr><td>14</td><td><a href="OTHL-ProTeamRoster.php#Hurricanes">Hurricanes</a></td><td>9</td><td>1</td><td>7</td><td>1</td><td><b>3</b></td><td>1</td><td>18</td><td>34</td><td>-16</td><td>0.167</td><td>1-2-1</td><td>0-5-0</td><td>1-7-1</td><td>1-2-1</td><td>0-5-0</td><td>L3</td><td>6</td></tr>
<tr><td>15</td><td><a href="OTHL-ProTeamRoster.php#Flyers">Flyers</a></td><td>5</td><td>1</td><td>4</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>15</td><td>-7</td><td>0.200</td><td>1-1-0</td><td>0-3-0</td><td>1-4-0</td><td>1-1-0</td><td>0-3-0</td><td>L3</td><td>7</td></tr>
<tr><td>16</td><td><a href="OTHL-ProTeamRoster.php#Penguins">Penguins</a></td><td>8</td><td>1</td><td>7</td><td>0</td><td><b>2</b></td><td>1</td><td>18</td><td>30</td><td>-12</td><td>0.125</td><td>1-5-0</td><td>0-2-0</td><td>1-7-0</td><td>1-5-0</td><td>0-2-0</td><td>L1</td><td>7</td></tr>
</tbody></table><br />
<h2 class="STHSStanding_H2Header">Western Conference</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Flames">Flames</a></td><td>8</td><td>7</td><td>1</td><td>0</td><td><b>14</b></td><td>6</td><td>27</td><td>12</td><td>15</td><td>0.875</td><td>3-1-0</td><td>4-0-0</td><td>7-1-0</td><td>3-1-0</td><td>4-0-0</td><td>W2</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Canucks">Canucks</a></td><td>6</td><td>6</td><td>0</td><td>0</td><td><b>12</b></td><td>4</td><td>23</td><td>12</td><td>11</td><td>1.000</td><td>3-0-0</td><td>3-0-0</td><td>6-0-0</td><td>3-0-0</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Ducks">Ducks</a></td><td>8</td><td>5</td><td>1</td><td>2</td><td><b>12</b></td><td>5</td><td>27</td><td>24</td><td>3</td><td>0.750</td><td>3-1-0</td><td>2-0-2</td><td>5-1-2</td><td>3-1-0</td><td>2-0-2</td><td>W2</td><td></td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#Jets">Jets</a></td><td>9</td><td>6</td><td>3</td><td>0</td><td><b>12</b></td><td>6</td><td>32</td><td>24</td><td>8</td><td>0.667</td><td>3-1-0</td><td>3-2-0</td><td>6-3-0</td><td>3-1-0</td><td>3-2-0</td><td>L1</td><td></td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Predators">Predators</a></td><td>7</td><td>5</td><td>2</td><td>0</td><td><b>10</b></td><td>4</td><td>18</td><td>15</td><td>3</td><td>0.714</td><td>3-1-0</td><td>2-1-0</td><td>5-2-0</td><td>3-1-0</td><td>2-1-0</td><td>L1</td><td></td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Blues">Blues</a></td><td>7</td><td>2</td><td>3</td><td>2</td><td><b>6</b></td><td>1</td><td>20</td><td>26</td><td>-6</td><td>0.429</td><td>0-1-2</td><td>2-2-0</td><td>2-3-2</td><td>0-1-2</td><td>2-2-0</td><td>L2</td><td>3</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#Sharks">Sharks</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>24</td><td>14</td><td>10</td><td>0.786</td><td>2-0-1</td><td>3-1-0</td><td>5-1-1</td><td>2-0-1</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#Oilers">Oilers</a></td><td>8</td><td>3</td><td>2</td><td>3</td><td><b>9</b></td><td>3</td><td>22</td><td>21</td><td>1</td><td>0.563</td><td>2-0-2</td><td>1-2-1</td><td>3-2-3</td><td>2-0-2</td><td>1-2-1</td><td>SOL1</td><td></td></tr>
<tr class="static"><td colspan="19"><hr /></td></tr>
<tr><td>9</td><td><a href="OTHL-ProTeamRoster.php#Coyotes">Coyotes</a></td><td>6</td><td>3</td><td>2</td><td>1</td><td><b>7</b></td><td>3</td><td>21</td><td>18</td><td>3</td><td>0.583</td><td>1-1-1</td><td>2-1-0</td><td>3-2-1</td><td>1-1-1</td><td>2-1-0</td><td>W1</td><td>2</td></tr>
<tr><td>10</td><td><a href="OTHL-ProTeamRoster.php#GoldenKnights">Golden Knights</a></td><td>8</td><td>3</td><td>4</td><td>1</td><td><b>7</b></td><td>3</td><td>17</td><td>24</td><td>-7</td><td>0.438</td><td>2-3-0</td><td>1-1-1</td><td>3-4-1</td><td>2-3-0</td><td>1-1-1</td><td>W1</td><td>2</td></tr>
<tr><td>11</td><td><a href="OTHL-ProTeamRoster.php#Stars">Stars</a></td><td>9</td><td>3</td><td>6</td><td>0</td><td><b>6</b></td><td>2</td><td>25</td><td>30</td><td>-5</td><td>0.333</td><td>1-2-0</td><td>2-4-0</td><td>3-6-0</td><td>1-2-0</td><td>2-4-0</td><td>W1</td><td>3</td></tr>
<tr><td>12</td><td><a href="OTHL-ProTeamRoster.php#Wild">Wild</a></td><td>7</td><td>2</td><td>4</td><td>1</td><td><b>5</b></td><td>2</td><td>16</td><td>18</td><td>-2</td><td>0.357</td><td>1-0-0</td><td>1-4-1</td><td>2-4-1</td><td>1-0-0</td><td>1-4-1</td><td>L1</td><td>4</td></tr>
<tr><td>13</td><td><a href="OTHL-ProTeamRoster.php#Blackhawks">Blackhawks</a></td><td>5</td><td>2</td><td>3</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>15</td><td>-3</td><td>0.400</td><td>1-3-0</td><td>1-0-0</td><td>2-3-0</td><td>1-3-0</td><td>1-0-0</td><td>L2</td><td>5</td></tr>
<tr><td>14</td><td><a href="OTHL-ProTeamRoster.php#Kings">Kings</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>23</td><td>-8</td><td>0.286</td><td>2-2-0</td><td>0-3-0</td><td>2-5-0</td><td>2-2-0</td><td>0-3-0</td><td>L1</td><td>5</td></tr>
<tr><td>15</td><td><a href="OTHL-ProTeamRoster.php#Avalanche">Avalanche</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>21</td><td>-10</td><td>0.286</td><td>1-3-0</td><td>1-2-0</td><td>2-5-0</td><td>1-3-0</td><td>1-2-0</td><td>L2</td><td>5</td></tr>
</tbody></table><br />
*Seeding 3 division leaders<br />
</div><div class="tabmain" id="tabmain3">
<h2 class="STHSStanding_H2Header">Adams Division</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Canadiens">Canadiens</a></td><td>7</td><td>5</td><td>0</td><td>2</td><td><b>12</b></td><td>4</td><td>23</td><td>18</td><td>5</td><td>0.857</td><td>2-0-2</td><td>3-0-0</td><td>5-0-2</td><td>2-0-2</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Panthers">Panthers</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>18</td><td>4</td><td>0.786</td><td>3-0-0</td><td>2-1-1</td><td>5-1-1</td><td>3-0-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Sabres">Sabres</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>4</td><td>23</td><td>15</td><td>8</td><td>0.625</td><td>1-1-2</td><td>3-1-0</td><td>4-2-2</td><td>1-1-2</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#RedWings">Red Wings</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>2</td><td>24</td><td>24</td><td>0</td><td>0.625</td><td>3-0-0</td><td>1-2-2</td><td>4-2-2</td><td>3-0-0</td><td>1-2-2</td><td>SOW1</td><td></td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Bruins">Bruins</a></td><td>7</td><td>4</td><td>2</td><td>1</td><td><b>9</b></td><td>2</td><td>20</td><td>20</td><td>0</td><td>0.643</td><td>2-1-0</td><td>2-1-1</td><td>4-2-1</td><td>2-1-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Senators">Senators</a></td><td>6</td><td>4</td><td>2</td><td>0</td><td><b>8</b></td><td>4</td><td>13</td><td>11</td><td>2</td><td>0.667</td><td>4-0-0</td><td>0-2-0</td><td>4-2-0</td><td>4-0-0</td><td>0-2-0</td><td>L1</td><td>1</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#Lightning">Lightning</a></td><td>7</td><td>3</td><td>4</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>20</td><td>-2</td><td>0.429</td><td>0-1-0</td><td>3-3-0</td><td>3-4-0</td><td>0-1-0</td><td>3-3-0</td><td>L1</td><td>3</td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#MapleLeafs">Maple Leafs</a></td><td>8</td><td>2</td><td>6</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>23</td><td>-7</td><td>0.250</td><td>1-4-0</td><td>1-2-0</td><td>2-6-0</td><td>1-4-0</td><td>1-2-0</td><td>L6</td><td>5</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Patrick Division</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Islanders">Islanders</a></td><td>7</td><td>7</td><td>0</td><td>0</td><td><b>14</b></td><td>6</td><td>24</td><td>11</td><td>13</td><td>1.000</td><td>5-0-0</td><td>2-0-0</td><td>7-0-0</td><td>5-0-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Capitals">Capitals</a></td><td>9</td><td>5</td><td>3</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>21</td><td>1</td><td>0.611</td><td>3-1-1</td><td>2-2-0</td><td>5-3-1</td><td>3-1-1</td><td>2-2-0</td><td>L1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Devils">Devils</a></td><td>7</td><td>4</td><td>3</td><td>0</td><td><b>8</b></td><td>4</td><td>21</td><td>19</td><td>2</td><td>0.571</td><td>2-2-0</td><td>2-1-0</td><td>4-3-0</td><td>2-2-0</td><td>2-1-0</td><td>L1</td><td>1</td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#BlueJackets">Blue Jackets</a></td><td>7</td><td>3</td><td>3</td><td>1</td><td><b>7</b></td><td>3</td><td>18</td><td>24</td><td>-6</td><td>0.500</td><td>1-3-0</td><td>2-0-1</td><td>3-3-1</td><td>1-3-0</td><td>2-0-1</td><td>W2</td><td>2</td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Rangers">Rangers</a></td><td>5</td><td>3</td><td>2</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0.600</td><td>1-1-0</td><td>2-1-0</td><td>3-2-0</td><td>1-1-0</td><td>2-1-0</td><td>W2</td><td>3</td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Hurricanes">Hurricanes</a></td><td>9</td><td>1</td><td>7</td><td>1</td><td><b>3</b></td><td>1</td><td>18</td><td>34</td><td>-16</td><td>0.167</td><td>1-2-1</td><td>0-5-0</td><td>1-7-1</td><td>1-2-1</td><td>0-5-0</td><td>L3</td><td>6</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#Flyers">Flyers</a></td><td>5</td><td>1</td><td>4</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>15</td><td>-7</td><td>0.200</td><td>1-1-0</td><td>0-3-0</td><td>1-4-0</td><td>1-1-0</td><td>0-3-0</td><td>L3</td><td>7</td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#Penguins">Penguins</a></td><td>8</td><td>1</td><td>7</td><td>0</td><td><b>2</b></td><td>1</td><td>18</td><td>30</td><td>-12</td><td>0.125</td><td>1-5-0</td><td>0-2-0</td><td>1-7-0</td><td>1-5-0</td><td>0-2-0</td><td>L1</td><td>7</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Norris Division</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Jets">Jets</a></td><td>9</td><td>6</td><td>3</td><td>0</td><td><b>12</b></td><td>6</td><td>32</td><td>24</td><td>8</td><td>0.667</td><td>3-1-0</td><td>3-2-0</td><td>6-3-0</td><td>3-1-0</td><td>3-2-0</td><td>L1</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Predators">Predators</a></td><td>7</td><td>5</td><td>2</td><td>0</td><td><b>10</b></td><td>4</td><td>18</td><td>15</td><td>3</td><td>0.714</td><td>3-1-0</td><td>2-1-0</td><td>5-2-0</td><td>3-1-0</td><td>2-1-0</td><td>L1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Blues">Blues</a></td><td>7</td><td>2</td><td>3</td><td>2</td><td><b>6</b></td><td>1</td><td>20</td><td>26</td><td>-6</td><td>0.429</td><td>0-1-2</td><td>2-2-0</td><td>2-3-2</td><td>0-1-2</td><td>2-2-0</td><td>L2</td><td>3</td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#Stars">Stars</a></td><td>9</td><td>3</td><td>6</td><td>0</td><td><b>6</b></td><td>2</td><td>25</td><td>30</td><td>-5</td><td>0.333</td><td>1-2-0</td><td>2-4-0</td><td>3-6-0</td><td>1-2-0</td><td>2-4-0</td><td>W1</td><td>3</td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Wild">Wild</a></td><td>7</td><td>2</td><td>4</td><td>1</td><td><b>5</b></td><td>2</td><td>16</td><td>18</td><td>-2</td><td>0.357</td><td>1-0-0</td><td>1-4-1</td><td>2-4-1</td><td>1-0-0</td><td>1-4-1</td><td>L1</td><td>4</td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Blackhawks">Blackhawks</a></td><td>5</td><td>2</td><td>3</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>15</td><td>-3</td><td>0.400</td><td>1-3-0</td><td>1-0-0</td><td>2-3-0</td><td>1-3-0</td><td>1-0-0</td><td>L2</td><td>5</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#Avalanche">Avalanche</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>21</td><td>-10</td><td>0.286</td><td>1-3-0</td><td>1-2-0</td><td>2-5-0</td><td>1-3-0</td><td>1-2-0</td><td>L2</td><td>5</td></tr>
</tbody></table>
<h2 class="STHSStanding_H2Header">Smythe Division</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Flames">Flames</a></td><td>8</td><td>7</td><td>1</td><td>0</td><td><b>14</b></td><td>6</td><td>27</td><td>12</td><td>15</td><td>0.875</td><td>3-1-0</td><td>4-0-0</td><td>7-1-0</td><td>3-1-0</td><td>4-0-0</td><td>W2</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Canucks">Canucks</a></td><td>6</td><td>6</td><td>0</td><td>0</td><td><b>12</b></td><td>4</td><td>23</td><td>12</td><td>11</td><td>1.000</td><td>3-0-0</td><td>3-0-0</td><td>6-0-0</td><td>3-0-0</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Ducks">Ducks</a></td><td>8</td><td>5</td><td>1</td><td>2</td><td><b>12</b></td><td>5</td><td>27</td><td>24</td><td>3</td><td>0.750</td><td>3-1-0</td><td>2-0-2</td><td>5-1-2</td><td>3-1-0</td><td>2-0-2</td><td>W2</td><td></td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#Sharks">Sharks</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>24</td><td>14</td><td>10</td><td>0.786</td><td>2-0-1</td><td>3-1-0</td><td>5-1-1</td><td>2-0-1</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Oilers">Oilers</a></td><td>8</td><td>3</td><td>2</td><td>3</td><td><b>9</b></td><td>3</td><td>22</td><td>21</td><td>1</td><td>0.563</td><td>2-0-2</td><td>1-2-1</td><td>3-2-3</td><td>2-0-2</td><td>1-2-1</td><td>SOL1</td><td></td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Coyotes">Coyotes</a></td><td>6</td><td>3</td><td>2</td><td>1</td><td><b>7</b></td><td>3</td><td>21</td><td>18</td><td>3</td><td>0.583</td><td>1-1-1</td><td>2-1-0</td><td>3-2-1</td><td>1-1-1</td><td>2-1-0</td><td>W1</td><td>2</td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#GoldenKnights">Golden Knights</a></td><td>8</td><td>3</td><td>4</td><td>1</td><td><b>7</b></td><td>3</td><td>17</td><td>24</td><td>-7</td><td>0.438</td><td>2-3-0</td><td>1-1-1</td><td>3-4-1</td><td>2-3-0</td><td>1-1-1</td><td>W1</td><td>2</td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#Kings">Kings</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>23</td><td>-8</td><td>0.286</td><td>2-2-0</td><td>0-3-0</td><td>2-5-0</td><td>2-2-0</td><td>0-3-0</td><td>L1</td><td>5</td></tr>
</tbody></table>
</div><div class="tabmain" id="tabmain4">
<h2 class="STHSStanding_H2Header">Overall</h2>
<table class="basictablesorter"><thead><tr><th class="STHSW35">PO</th><th class="STHSW200">Teams</th><th class="STHSW30">GP</th><th class="STHSW30">W</th><th class="STHSW30">L</th><th class="STHSW30">OTL</th><th class="STHSW30">P</th><th class="STHSW30">ROW</th><th class="STHSW30">GF</th><th class="STHSW30">GA</th><th class="STHSW30">Diff</th><th class="STHSW45">PCT</th><th class="STHSW75">Home</th><th class="STHSW75">Visitor</th><th class="STHSW75">Last 10</th><th class="STHSW75">Home L10</th><th class="STHSW75">Visitor L10</th><th class="STHSW30">STK</th><th class="STHSW30">PR</th></tr></thead>
<tbody>
<tr><td>1</td><td><a href="OTHL-ProTeamRoster.php#Islanders">Islanders</a></td><td>7</td><td>7</td><td>0</td><td>0</td><td><b>14</b></td><td>6</td><td>24</td><td>11</td><td>13</td><td>1.000</td><td>5-0-0</td><td>2-0-0</td><td>7-0-0</td><td>5-0-0</td><td>2-0-0</td><td>W2</td><td></td></tr>
<tr><td>2</td><td><a href="OTHL-ProTeamRoster.php#Flames">Flames</a></td><td>8</td><td>7</td><td>1</td><td>0</td><td><b>14</b></td><td>6</td><td>27</td><td>12</td><td>15</td><td>0.875</td><td>3-1-0</td><td>4-0-0</td><td>7-1-0</td><td>3-1-0</td><td>4-0-0</td><td>W2</td><td></td></tr>
<tr><td>3</td><td><a href="OTHL-ProTeamRoster.php#Canucks">Canucks</a></td><td>6</td><td>6</td><td>0</td><td>0</td><td><b>12</b></td><td>4</td><td>23</td><td>12</td><td>11</td><td>1.000</td><td>3-0-0</td><td>3-0-0</td><td>6-0-0</td><td>3-0-0</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>4</td><td><a href="OTHL-ProTeamRoster.php#Canadiens">Canadiens</a></td><td>7</td><td>5</td><td>0</td><td>2</td><td><b>12</b></td><td>4</td><td>23</td><td>18</td><td>5</td><td>0.857</td><td>2-0-2</td><td>3-0-0</td><td>5-0-2</td><td>2-0-2</td><td>3-0-0</td><td>W1</td><td></td></tr>
<tr><td>5</td><td><a href="OTHL-ProTeamRoster.php#Ducks">Ducks</a></td><td>8</td><td>5</td><td>1</td><td>2</td><td><b>12</b></td><td>5</td><td>27</td><td>24</td><td>3</td><td>0.750</td><td>3-1-0</td><td>2-0-2</td><td>5-1-2</td><td>3-1-0</td><td>2-0-2</td><td>W2</td><td></td></tr>
<tr><td>6</td><td><a href="OTHL-ProTeamRoster.php#Jets">Jets</a></td><td>9</td><td>6</td><td>3</td><td>0</td><td><b>12</b></td><td>6</td><td>32</td><td>24</td><td>8</td><td>0.667</td><td>3-1-0</td><td>3-2-0</td><td>6-3-0</td><td>3-1-0</td><td>3-2-0</td><td>L1</td><td></td></tr>
<tr><td>7</td><td><a href="OTHL-ProTeamRoster.php#Sharks">Sharks</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>24</td><td>14</td><td>10</td><td>0.786</td><td>2-0-1</td><td>3-1-0</td><td>5-1-1</td><td>2-0-1</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>8</td><td><a href="OTHL-ProTeamRoster.php#Panthers">Panthers</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>18</td><td>4</td><td>0.786</td><td>3-0-0</td><td>2-1-1</td><td>5-1-1</td><td>3-0-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>9</td><td><a href="OTHL-ProTeamRoster.php#Capitals">Capitals</a></td><td>9</td><td>5</td><td>3</td><td>1</td><td><b>11</b></td><td>5</td><td>22</td><td>21</td><td>1</td><td>0.611</td><td>3-1-1</td><td>2-2-0</td><td>5-3-1</td><td>3-1-1</td><td>2-2-0</td><td>L1</td><td></td></tr>
<tr><td>10</td><td><a href="OTHL-ProTeamRoster.php#Predators">Predators</a></td><td>7</td><td>5</td><td>2</td><td>0</td><td><b>10</b></td><td>4</td><td>18</td><td>15</td><td>3</td><td>0.714</td><td>3-1-0</td><td>2-1-0</td><td>5-2-0</td><td>3-1-0</td><td>2-1-0</td><td>L1</td><td></td></tr>
<tr><td>11</td><td><a href="OTHL-ProTeamRoster.php#Sabres">Sabres</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>4</td><td>23</td><td>15</td><td>8</td><td>0.625</td><td>1-1-2</td><td>3-1-0</td><td>4-2-2</td><td>1-1-2</td><td>3-1-0</td><td>W1</td><td></td></tr>
<tr><td>12</td><td><a href="OTHL-ProTeamRoster.php#RedWings">Red Wings</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>10</b></td><td>2</td><td>24</td><td>24</td><td>0</td><td>0.625</td><td>3-0-0</td><td>1-2-2</td><td>4-2-2</td><td>3-0-0</td><td>1-2-2</td><td>SOW1</td><td></td></tr>
<tr><td>13</td><td><a href="OTHL-ProTeamRoster.php#Bruins">Bruins</a></td><td>7</td><td>4</td><td>2</td><td>1</td><td><b>9</b></td><td>2</td><td>20</td><td>20</td><td>0</td><td>0.643</td><td>2-1-0</td><td>2-1-1</td><td>4-2-1</td><td>2-1-0</td><td>2-1-1</td><td>W1</td><td></td></tr>
<tr><td>14</td><td><a href="OTHL-ProTeamRoster.php#Oilers">Oilers</a></td><td>8</td><td>3</td><td>2</td><td>3</td><td><b>9</b></td><td>3</td><td>22</td><td>21</td><td>1</td><td>0.563</td><td>2-0-2</td><td>1-2-1</td><td>3-2-3</td><td>2-0-2</td><td>1-2-1</td><td>SOL1</td><td></td></tr>
<tr><td>15</td><td><a href="OTHL-ProTeamRoster.php#Senators">Senators</a></td><td>6</td><td>4</td><td>2</td><td>0</td><td><b>8</b></td><td>4</td><td>13</td><td>11</td><td>2</td><td>0.667</td><td>4-0-0</td><td>0-2-0</td><td>4-2-0</td><td>4-0-0</td><td>0-2-0</td><td>L1</td><td>1</td></tr>
<tr><td>16</td><td><a href="OTHL-ProTeamRoster.php#Devils">Devils</a></td><td>7</td><td>4</td><td>3</td><td>0</td><td><b>8</b></td><td>4</td><td>21</td><td>19</td><td>2</td><td>0.571</td><td>2-2-0</td><td>2-1-0</td><td>4-3-0</td><td>2-2-0</td><td>2-1-0</td><td>L1</td><td>1</td></tr>
<tr><td>17</td><td><a href="OTHL-ProTeamRoster.php#Coyotes">Coyotes</a></td><td>6</td><td>3</td><td>2</td><td>1</td><td><b>7</b></td><td>3</td><td>21</td><td>18</td><td>3</td><td>0.583</td><td>1-1-1</td><td>2-1-0</td><td>3-2-1</td><td>1-1-1</td><td>2-1-0</td><td>W1</td><td>2</td></tr>
<tr><td>18</td><td><a href="OTHL-ProTeamRoster.php#BlueJackets">Blue Jackets</a></td><td>7</td><td>3</td><td>3</td><td>1</td><td><b>7</b></td><td>3</td><td>18</td><td>24</td><td>-6</td><td>0.500</td><td>1-3-0</td><td>2-0-1</td><td>3-3-1</td><td>1-3-0</td><td>2-0-1</td><td>W2</td><td>2</td></tr>
<tr><td>19</td><td><a href="OTHL-ProTeamRoster.php#GoldenKnights">Golden Knights</a></td><td>8</td><td>3</td><td>4</td><td>1</td><td><b>7</b></td><td>3</td><td>17</td><td>24</td><td>-7</td><td>0.438</td><td>2-3-0</td><td>1-1-1</td><td>3-4-1</td><td>2-3-0</td><td>1-1-1</td><td>W1</td><td>2</td></tr>
<tr><td>20</td><td><a href="OTHL-ProTeamRoster.php#Rangers">Rangers</a></td><td>5</td><td>3</td><td>2</td><td>0</td><td><b>6</b></td><td>2</td><td>13</td><td>11</td><td>2</td><td>0.600</td><td>1-1-0</td><td>2-1-0</td><td>3-2-0</td><td>1-1-0</td><td>2-1-0</td><td>W2</td><td>3</td></tr>
<tr><td>21</td><td><a href="OTHL-ProTeamRoster.php#Lightning">Lightning</a></td><td>7</td><td>3</td><td>4</td><td>0</td><td><b>6</b></td><td>3</td><td>18</td><td>20</td><td>-2</td><td>0.429</td><td>0-1-0</td><td>3-3-0</td><td>3-4-0</td><td>0-1-0</td><td>3-3-0</td><td>L1</td><td>3</td></tr>
<tr><td>22</td><td><a href="OTHL-ProTeamRoster.php#Blues">Blues</a></td><td>7</td><td>2</td><td>3</td><td>2</td><td><b>6</b></td><td>1</td><td>20</td><td>26</td><td>-6</td><td>0.429</td><td>0-1-2</td><td>2-2-0</td><td>2-3-2</td><td>0-1-2</td><td>2-2-0</td><td>L2</td><td>3</td></tr>
<tr><td>23</td><td><a href="OTHL-ProTeamRoster.php#Stars">Stars</a></td><td>9</td><td>3</td><td>6</td><td>0</td><td><b>6</b></td><td>2</td><td>25</td><td>30</td><td>-5</td><td>0.333</td><td>1-2-0</td><td>2-4-0</td><td>3-6-0</td><td>1-2-0</td><td>2-4-0</td><td>W1</td><td>3</td></tr>
<tr><td>24</td><td><a href="OTHL-ProTeamRoster.php#Wild">Wild</a></td><td>7</td><td>2</td><td>4</td><td>1</td><td><b>5</b></td><td>2</td><td>16</td><td>18</td><td>-2</td><td>0.357</td><td>1-0-0</td><td>1-4-1</td><td>2-4-1</td><td>1-0-0</td><td>1-4-1</td><td>L1</td><td>4</td></tr>
<tr><td>25</td><td><a href="OTHL-ProTeamRoster.php#Blackhawks">Blackhawks</a></td><td>5</td><td>2</td><td>3</td><td>0</td><td><b>4</b></td><td>2</td><td>12</td><td>15</td><td>-3</td><td>0.400</td><td>1-3-0</td><td>1-0-0</td><td>2-3-0</td><td>1-3-0</td><td>1-0-0</td><td>L2</td><td>5</td></tr>
<tr><td>26</td><td><a href="OTHL-ProTeamRoster.php#Kings">Kings</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>15</td><td>23</td><td>-8</td><td>0.286</td><td>2-2-0</td><td>0-3-0</td><td>2-5-0</td><td>2-2-0</td><td>0-3-0</td><td>L1</td><td>5</td></tr>
<tr><td>27</td><td><a href="OTHL-ProTeamRoster.php#Avalanche">Avalanche</a></td><td>7</td><td>2</td><td>5</td><td>0</td><td><b>4</b></td><td>2</td><td>11</td><td>21</td><td>-10</td><td>0.286</td><td>1-3-0</td><td>1-2-0</td><td>2-5-0</td><td>1-3-0</td><td>1-2-0</td><td>L2</td><td>5</td></tr>
<tr><td>28</td><td><a href="OTHL-ProTeamRoster.php#MapleLeafs">Maple Leafs</a></td><td>8</td><td>2</td><td>6</td><td>0</td><td><b>4</b></td><td>2</td><td>16</td><td>23</td><td>-7</td><td>0.250</td><td>1-4-0</td><td>1-2-0</td><td>2-6-0</td><td>1-4-0</td><td>1-2-0</td><td>L6</td><td>5</td></tr>
<tr><td>29</td><td><a href="OTHL-ProTeamRoster.php#Hurricanes">Hurricanes</a></td><td>9</td><td>1</td><td>7</td><td>1</td><td><b>3</b></td><td>1</td><td>18</td><td>34</td><td>-16</td><td>0.167</td><td>1-2-1</td><td>0-5-0</td><td>1-7-1</td><td>1-2-1</td><td>0-5-0</td><td>L3</td><td>6</td></tr>
<tr><td>30</td><td><a href="OTHL-ProTeamRoster.php#Flyers">Flyers</a></td><td>5</td><td>1</td><td>4</td><td>0</td><td><b>2</b></td><td>1</td><td>8</td><td>15</td><td>-7</td><td>0.200</td><td>1-1-0</td><td>0-3-0</td><td>1-4-0</td><td>1-1-0</td><td>0-3-0</td><td>L3</td><td>7</td></tr>
<tr><td>31</td><td><a href="OTHL-ProTeamRoster.php#Penguins">Penguins</a></td><td>8</td><td>1</td><td>7</td><td>0</td><td><b>2</b></td><td>1</td><td>18</td><td>30</td><td>-12</td><td>0.125</td><td>1-5-0</td><td>0-2-0</td><td>1-7-0</td><td>1-5-0</td><td>0-2-0</td><td>L1</td><td>7</td></tr>
</tbody></table></div></div></div>
<h2 class="STHSStanding_PointSystem">Point System</h2>
<b>Win :</b> 2 -- <b>Loss :</b> 0 -- <b>OT Win :</b> 2 -- <b>OT Loss :</b> 1 -- <b>SO Win :</b> 2 -- <b>SO Loss :</b> 1<br /><br />P.S. The simulator only uses points to give the title. If two team have the same amount of point, none of them will be award the title until your simulate the last game/day of your season.
<?php include "Footer.php";?>
