<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<script src="STHSMain.js"></script>
<title>OTHL - Pro Leaders</title>
<script src="OTHL.js"></script>
<meta name="author" content="Simon Tremblay, sths.simont.info" />
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="Decription" content="Tyler Bell - STHS - Version : 3.1.6.6" />
<link href="STHSMain.css" rel="stylesheet" type="text/css" />
<style>
@media screen and (max-width: 1200px) {
.STHSWarning {display:block;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(1){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(2){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(3){display:none;}
}
@media screen and (max-width: 1060px) {
.STHSScoring_PlayersTable1 tbody td:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(6){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(7){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-last-child(8){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-last-child(8){display:none;}
}
@media screen and (max-width: 960px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(3){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(4){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(4){display:none;}
}
@media screen and (max-width: 890px) {
.STHSW10 {display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(13){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(13){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(15){display:none;}
.STHSScoring_PlayersTable1 tbody td:nth-child(16){display:none;}
.STHSScoring_PlayersTable1 thead th:nth-child(16){display:none;}
.STHSScoring_GoaliesTable tbody td:nth-last-child(5){display:none;}
.STHSScoring_GoaliesTable thead th:nth-last-child(5){display:none;}
}</style>
<link href="OTHL.css" rel="stylesheet" type="text/css" />
<?php If (file_exists("STHSMain-CSSOverwrite.css") == true){echo "<link href=\"STHSMain-CSSOverwrite.css\" rel=\"stylesheet\" type=\"text/css\" />";}?>
</head><body>
<?php $LeagueName = (string)"";
$DatabaseFile = (string)"OTHL-STHS.db";
$LangOverwrite = (boolean)FALSE;
$CareerStatDatabaseFile = (string)"OTHL-STHSCareerStat.db";
$lang = (string)"en"; /* The $lang option must be either "en" or "fr" */
if(isset($_GET['Lang'])){$lang  = filter_var($_GET['Lang'], FILTER_SANITIZE_STRING, FILTER_FLAG_STRIP_LOW || FILTER_FLAG_STRIP_HIGH);$LangOverwrite=TRUE;}  /* Allow Users Language Overwrite */
If ($lang == "fr"){include 'LanguageFR.php';}else{include 'LanguageEN.php';}
$db = new SQLite3($DatabaseFile);
$Active = 1; /* Show Webpage Top Menu */
include "Menu.php";?>
<script>$(function(){$("table").basictablesorter()});$(function (){$("table").stickyTableHeaders();});</script>
<table class="basictablesorter STHSScoring_PlayersTable1"><thead><tr><th class="STHSW25">#</th><th class="STHSW200">Player Name</th><th class="STHSW10">F</th><th class="STHSW10">D</th><th class="STHSW25">GP</th><th class="STHSW25">G</th><th class="STHSW25">A</th><th class="STHSW25">P</th><th class="STHSW25">+/-</th><th class="STHSW25">PIM</th><th class="STHSW25">PM5</th><th class="STHSW25">HIT</th><th class="STHSW25">HTT</th><th class="STHSW25">SHT</th><th class="STHSW25">OSB</th><th class="STHSW25">OSM</th><th class="STHSW55">SHT %</th><th class="STHSW25">SB</th><th class="STHSW35">MP</th><th class="STHSW35">AMG</th><th class="STHSW25">PPG</th><th class="STHSW25">PPA</th><th class="STHSW25">PPP</th><th class="STHSW25">PPS</th><th class="STHSW25">PPM</th><th class="STHSW25">PKG</th><th class="STHSW25">PKA</th><th class="STHSW25">PKP</th><th class="STHSW25">PKS</th><th class="STHSW25">PKM</th></tr></thead>
<tr><td>1</td><td><a href="PlayerReport.php?Player=352">Ryan Nugent-Hopkins (EDM)</a></td><td>X</td><td></td><td>8</td><td>6</td><td>6</td><td><b>12</b></td><td>5</td><td>2</td><td>0</td><td>5</td><td>17</td><td>29</td><td>9</td><td>31</td><td>20.69%</td><td>0</td><td>184</td><td>22.98</td><td>2</td><td>2</td><td>4</td><td>8</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td></tr>
<tr><td>2</td><td><a href="PlayerReport.php?Player=2446">Evgeny Kuznetsov (SJS)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>8</td><td><b>12</b></td><td>4</td><td>0</td><td>0</td><td>8</td><td>21</td><td>24</td><td>5</td><td>10</td><td>16.67%</td><td>0</td><td>142</td><td>20.25</td><td>1</td><td>4</td><td>5</td><td>9</td><td>30</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>3</td><td><a href="PlayerReport.php?Player=161">Jonathan Toews (WPG)</a></td><td>X</td><td></td><td>9</td><td>7</td><td>4</td><td><b>11</b></td><td>5</td><td>0</td><td>0</td><td>8</td><td>25</td><td>38</td><td>9</td><td>33</td><td>18.42%</td><td>1</td><td>195</td><td>21.71</td><td>1</td><td>1</td><td>2</td><td>7</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>4</td><td><a href="PlayerReport.php?Player=699">Taylor Hall (CGY)</a></td><td>X</td><td></td><td>8</td><td>3</td><td>7</td><td><b>10</b></td><td>6</td><td>0</td><td>0</td><td>3</td><td>20</td><td>29</td><td>11</td><td>23</td><td>10.34%</td><td>2</td><td>157</td><td>19.59</td><td>1</td><td>3</td><td>4</td><td>9</td><td>34</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>5</td><td><a href="PlayerReport.php?Player=294">Erik Karlsson (CGY)</a></td><td></td><td>X</td><td>8</td><td>2</td><td>8</td><td><b>10</b></td><td>10</td><td>6</td><td>0</td><td>11</td><td>15</td><td>18</td><td>2</td><td>10</td><td>11.11%</td><td>8</td><td>190</td><td>23.73</td><td>2</td><td>1</td><td>3</td><td>12</td><td>36</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td></tr>
<tr><td>6</td><td><a href="PlayerReport.php?Player=387">Blake Wheeler (EDM)</a></td><td>X</td><td></td><td>8</td><td>5</td><td>4</td><td><b>9</b></td><td>5</td><td>9</td><td>5</td><td>21</td><td>8</td><td>26</td><td>9</td><td>10</td><td>19.23%</td><td>0</td><td>173</td><td>21.59</td><td>0</td><td>1</td><td>1</td><td>3</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td>7</td><td><a href="PlayerReport.php?Player=2669">Viktor Arvidsson (CGY)</a></td><td>X</td><td></td><td>8</td><td>5</td><td>4</td><td><b>9</b></td><td>4</td><td>0</td><td>0</td><td>6</td><td>11</td><td>32</td><td>11</td><td>22</td><td>15.63%</td><td>2</td><td>159</td><td>19.94</td><td>1</td><td>1</td><td>2</td><td>5</td><td>37</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>8</td><td><a href="PlayerReport.php?Player=26">Jack Eichel (WSH)</a></td><td>X</td><td></td><td>9</td><td>5</td><td>4</td><td><b>9</b></td><td>2</td><td>0</td><td>0</td><td>5</td><td>19</td><td>32</td><td>8</td><td>19</td><td>15.63%</td><td>0</td><td>176</td><td>19.56</td><td>1</td><td>1</td><td>2</td><td>7</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td>9</td><td><a href="PlayerReport.php?Player=155">Dustin Brown (EDM)</a></td><td>X</td><td></td><td>8</td><td>4</td><td>5</td><td><b>9</b></td><td>2</td><td>6</td><td>0</td><td>17</td><td>7</td><td>33</td><td>5</td><td>19</td><td>12.12%</td><td>2</td><td>164</td><td>20.50</td><td>2</td><td>2</td><td>4</td><td>8</td><td>32</td><td>0</td><td>0</td><td>0</td><td>3</td><td>18</td></tr>
<tr><td>10</td><td><a href="PlayerReport.php?Player=1746">Mika Zibanejad (ARI)</a></td><td>X</td><td></td><td>6</td><td>3</td><td>6</td><td><b>9</b></td><td>3</td><td>0</td><td>0</td><td>15</td><td>23</td><td>26</td><td>6</td><td>18</td><td>11.54%</td><td>1</td><td>130</td><td>21.59</td><td>0</td><td>2</td><td>2</td><td>6</td><td>14</td><td>1</td><td>0</td><td>1</td><td>1</td><td>28</td></tr>
<tr><td>11</td><td><a href="PlayerReport.php?Player=2438">Aleksander Barkov (SJS)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>6</td><td><b>9</b></td><td>4</td><td>8</td><td>0</td><td>7</td><td>17</td><td>40</td><td>15</td><td>37</td><td>7.50%</td><td>1</td><td>155</td><td>22.14</td><td>1</td><td>3</td><td>4</td><td>12</td><td>31</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td>12</td><td><a href="PlayerReport.php?Player=60">Patrice Bergeron (DAL)</a></td><td>X</td><td></td><td>9</td><td>3</td><td>6</td><td><b>9</b></td><td>-4</td><td>0</td><td>0</td><td>9</td><td>30</td><td>39</td><td>11</td><td>27</td><td>7.69%</td><td>0</td><td>176</td><td>19.54</td><td>1</td><td>3</td><td>4</td><td>7</td><td>32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>4</td></tr>
<tr><td>13</td><td><a href="PlayerReport.php?Player=1524">T.J. Oshie (WSH)</a></td><td>X</td><td></td><td>9</td><td>3</td><td>6</td><td><b>9</b></td><td>1</td><td>2</td><td>0</td><td>11</td><td>9</td><td>34</td><td>14</td><td>18</td><td>8.82%</td><td>1</td><td>173</td><td>19.24</td><td>1</td><td>2</td><td>3</td><td>9</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>14</td><td><a href="PlayerReport.php?Player=2613">Phillip Danault (CGY)</a></td><td>X</td><td></td><td>8</td><td>2</td><td>7</td><td><b>9</b></td><td>4</td><td>2</td><td>0</td><td>11</td><td>21</td><td>23</td><td>5</td><td>25</td><td>8.70%</td><td>0</td><td>163</td><td>20.32</td><td>0</td><td>1</td><td>1</td><td>4</td><td>30</td><td>0</td><td>0</td><td>0</td><td>1</td><td>15</td></tr>
<tr><td>15</td><td><a href="PlayerReport.php?Player=610">Kevin Shattenkirk (WPG)</a></td><td></td><td>X</td><td>9</td><td>1</td><td>8</td><td><b>9</b></td><td>2</td><td>6</td><td>0</td><td>11</td><td>6</td><td>13</td><td>6</td><td>7</td><td>7.69%</td><td>10</td><td>169</td><td>18.83</td><td>1</td><td>1</td><td>2</td><td>8</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>18</td></tr>
<tr><td>16</td><td><a href="PlayerReport.php?Player=2178">Sami Vatanen (WPG)</a></td><td></td><td>X</td><td>9</td><td>0</td><td>9</td><td><b>9</b></td><td>6</td><td>0</td><td>0</td><td>18</td><td>7</td><td>14</td><td>8</td><td>13</td><td>0.00%</td><td>18</td><td>223</td><td>24.78</td><td>0</td><td>2</td><td>2</td><td>11</td><td>30</td><td>0</td><td>0</td><td>0</td><td>1</td><td>19</td></tr>
<tr><td>17</td><td><a href="PlayerReport.php?Player=497">Travis Zajac (ANH)</a></td><td>X</td><td></td><td>8</td><td>6</td><td>2</td><td><b>8</b></td><td>7</td><td>2</td><td>0</td><td>9</td><td>15</td><td>26</td><td>2</td><td>20</td><td>23.08%</td><td>2</td><td>121</td><td>15.14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td><td>0</td><td>2</td><td>2</td><td>18</td></tr>
<tr><td>18</td><td><a href="PlayerReport.php?Player=676">Jeff Carter (MTL)</a></td><td>X</td><td></td><td>7</td><td>5</td><td>3</td><td><b>8</b></td><td>3</td><td>4</td><td>0</td><td>24</td><td>19</td><td>34</td><td>10</td><td>22</td><td>14.71%</td><td>1</td><td>143</td><td>20.36</td><td>2</td><td>1</td><td>3</td><td>7</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>8</td></tr>
<tr><td>19</td><td><a href="PlayerReport.php?Player=593">Zach Parise (DAL)</a></td><td>X</td><td></td><td>9</td><td>5</td><td>3</td><td><b>8</b></td><td>-4</td><td>2</td><td>0</td><td>7</td><td>15</td><td>33</td><td>11</td><td>31</td><td>15.15%</td><td>0</td><td>172</td><td>19.13</td><td>4</td><td>0</td><td>4</td><td>8</td><td>32</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>20</td><td><a href="PlayerReport.php?Player=2660">Ryan O'Reilly (NYI)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>4</td><td><b>8</b></td><td>2</td><td>0</td><td>0</td><td>13</td><td>17</td><td>26</td><td>5</td><td>17</td><td>15.38%</td><td>2</td><td>163</td><td>23.26</td><td>0</td><td>2</td><td>2</td><td>4</td><td>22</td><td>0</td><td>0</td><td>0</td><td>0</td><td>21</td></tr>
<tr><td>21</td><td><a href="PlayerReport.php?Player=1705">Casey Cizikas (TOR)</a></td><td>X</td><td></td><td>8</td><td>4</td><td>4</td><td><b>8</b></td><td>7</td><td>2</td><td>0</td><td>9</td><td>27</td><td>29</td><td>11</td><td>27</td><td>13.79%</td><td>0</td><td>139</td><td>17.34</td><td>0</td><td>2</td><td>2</td><td>3</td><td>17</td><td>0</td><td>0</td><td>0</td><td>1</td><td>27</td></tr>
<tr><td>22</td><td><a href="PlayerReport.php?Player=263">Matthew Tkachuk (WPG)</a></td><td>X</td><td></td><td>9</td><td>4</td><td>4</td><td><b>8</b></td><td>6</td><td>6</td><td>0</td><td>18</td><td>10</td><td>38</td><td>8</td><td>17</td><td>10.53%</td><td>0</td><td>179</td><td>19.89</td><td>2</td><td>1</td><td>3</td><td>6</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td></tr>
<tr><td>23</td><td><a href="PlayerReport.php?Player=211">Alex DeBrincat (MTL)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>5</td><td><b>8</b></td><td>3</td><td>0</td><td>0</td><td>10</td><td>10</td><td>35</td><td>8</td><td>17</td><td>8.57%</td><td>0</td><td>135</td><td>19.24</td><td>0</td><td>2</td><td>2</td><td>7</td><td>25</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>24</td><td><a href="PlayerReport.php?Player=423">Mats Zuccarello (CLB)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>5</td><td><b>8</b></td><td>-2</td><td>4</td><td>0</td><td>9</td><td>22</td><td>13</td><td>2</td><td>25</td><td>23.08%</td><td>3</td><td>152</td><td>21.74</td><td>2</td><td>1</td><td>3</td><td>2</td><td>17</td><td>0</td><td>0</td><td>0</td><td>1</td><td>27</td></tr>
<tr><td>25</td><td><a href="PlayerReport.php?Player=36">Dylan Larkin (CGY)</a></td><td>X</td><td></td><td>8</td><td>3</td><td>5</td><td><b>8</b></td><td>5</td><td>0</td><td>0</td><td>4</td><td>24</td><td>34</td><td>10</td><td>25</td><td>8.82%</td><td>1</td><td>169</td><td>21.09</td><td>1</td><td>2</td><td>3</td><td>9</td><td>34</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td>26</td><td><a href="PlayerReport.php?Player=23">Paul Stastny (CAR)</a></td><td>X</td><td></td><td>9</td><td>3</td><td>5</td><td><b>8</b></td><td>2</td><td>0</td><td>0</td><td>4</td><td>30</td><td>34</td><td>11</td><td>17</td><td>8.82%</td><td>5</td><td>203</td><td>22.56</td><td>0</td><td>1</td><td>1</td><td>3</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>38</td></tr>
<tr><td>27</td><td><a href="PlayerReport.php?Player=217">Josh Morrissey (ANH)</a></td><td></td><td>X</td><td>8</td><td>2</td><td>6</td><td><b>8</b></td><td>4</td><td>17</td><td>5</td><td>8</td><td>12</td><td>15</td><td>3</td><td>7</td><td>13.33%</td><td>8</td><td>194</td><td>24.24</td><td>0</td><td>1</td><td>1</td><td>5</td><td>27</td><td>0</td><td>1</td><td>1</td><td>0</td><td>17</td></tr>
<tr><td>28</td><td><a href="PlayerReport.php?Player=328">Eric Staal (WPG)</a></td><td>X</td><td></td><td>9</td><td>2</td><td>6</td><td><b>8</b></td><td>4</td><td>2</td><td>0</td><td>11</td><td>33</td><td>30</td><td>4</td><td>14</td><td>6.67%</td><td>0</td><td>190</td><td>21.15</td><td>0</td><td>3</td><td>3</td><td>10</td><td>36</td><td>0</td><td>0</td><td>0</td><td>1</td><td>24</td></tr>
<tr><td>29</td><td><a href="PlayerReport.php?Player=319">Tyler Myers (VAN)</a></td><td></td><td>X</td><td>6</td><td>0</td><td>8</td><td><b>8</b></td><td>8</td><td>4</td><td>0</td><td>20</td><td>1</td><td>5</td><td>1</td><td>2</td><td>0.00%</td><td>11</td><td>148</td><td>24.70</td><td>0</td><td>1</td><td>1</td><td>3</td><td>14</td><td>0</td><td>0</td><td>0</td><td>0</td><td>14</td></tr>
<tr><td>30</td><td><a href="PlayerReport.php?Player=364">Tyler Ennis (STL)</a></td><td>X</td><td></td><td>7</td><td>0</td><td>8</td><td><b>8</b></td><td>3</td><td>0</td><td>0</td><td>1</td><td>9</td><td>17</td><td>4</td><td>19</td><td>0.00%</td><td>0</td><td>108</td><td>15.48</td><td>0</td><td>1</td><td>1</td><td>3</td><td>13</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td>31</td><td><a href="PlayerReport.php?Player=56">Tyler Bozak (FLA)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>3</td><td><b>7</b></td><td>3</td><td>0</td><td>0</td><td>6</td><td>10</td><td>14</td><td>5</td><td>13</td><td>28.57%</td><td>1</td><td>125</td><td>17.80</td><td>1</td><td>0</td><td>1</td><td>2</td><td>21</td><td>0</td><td>0</td><td>0</td><td>0</td><td>20</td></tr>
<tr><td>32</td><td><a href="PlayerReport.php?Player=74">Elias Pettersson (R) (CLB)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>3</td><td><b>7</b></td><td>-1</td><td>0</td><td>0</td><td>5</td><td>17</td><td>28</td><td>10</td><td>15</td><td>14.29%</td><td>0</td><td>126</td><td>17.95</td><td>0</td><td>2</td><td>2</td><td>6</td><td>16</td><td>0</td><td>0</td><td>0</td><td>1</td><td>8</td></tr>
<tr><td>33</td><td><a href="PlayerReport.php?Player=456">Mikko Koivu (COL)</a></td><td>X</td><td></td><td>7</td><td>3</td><td>4</td><td><b>7</b></td><td>1</td><td>0</td><td>0</td><td>5</td><td>19</td><td>22</td><td>4</td><td>16</td><td>13.64%</td><td>5</td><td>141</td><td>20.13</td><td>0</td><td>0</td><td>0</td><td>3</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>10</td></tr>
<tr><td>34</td><td><a href="PlayerReport.php?Player=619">Wayne Simmonds (CAR)</a></td><td>X</td><td></td><td>9</td><td>3</td><td>4</td><td><b>7</b></td><td>1</td><td>2</td><td>0</td><td>15</td><td>15</td><td>30</td><td>9</td><td>23</td><td>10.00%</td><td>2</td><td>161</td><td>17.89</td><td>1</td><td>0</td><td>1</td><td>5</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>2</td></tr>
<tr><td>35</td><td><a href="PlayerReport.php?Player=152">Mikko Rantanen (VAN)</a></td><td>X</td><td></td><td>6</td><td>2</td><td>5</td><td><b>7</b></td><td>3</td><td>0</td><td>0</td><td>9</td><td>8</td><td>29</td><td>7</td><td>16</td><td>6.90%</td><td>0</td><td>126</td><td>20.96</td><td>0</td><td>1</td><td>1</td><td>3</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td>36</td><td><a href="PlayerReport.php?Player=567">Cam Fowler (PIT)</a></td><td></td><td>X</td><td>6</td><td>2</td><td>5</td><td><b>7</b></td><td>-1</td><td>0</td><td>0</td><td>5</td><td>8</td><td>13</td><td>4</td><td>10</td><td>15.38%</td><td>8</td><td>131</td><td>21.90</td><td>2</td><td>1</td><td>3</td><td>7</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>7</td></tr>
<tr><td>37</td><td><a href="PlayerReport.php?Player=1571">Leon Draisaitl (ARI)</a></td><td>X</td><td></td><td>6</td><td>2</td><td>5</td><td><b>7</b></td><td>1</td><td>4</td><td>0</td><td>7</td><td>13</td><td>36</td><td>5</td><td>30</td><td>5.56%</td><td>0</td><td>130</td><td>21.71</td><td>1</td><td>3</td><td>4</td><td>7</td><td>18</td><td>0</td><td>0</td><td>0</td><td>1</td><td>11</td></tr>
<tr><td>38</td><td><a href="PlayerReport.php?Player=1720">Gustav Nyquist (VAN)</a></td><td>X</td><td></td><td>6</td><td>2</td><td>5</td><td><b>7</b></td><td>5</td><td>2</td><td>0</td><td>3</td><td>7</td><td>15</td><td>3</td><td>9</td><td>13.33%</td><td>0</td><td>74</td><td>12.35</td><td>0</td><td>1</td><td>1</td><td>1</td><td>2</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>39</td><td><a href="PlayerReport.php?Player=421">Patrick Kane (COL)</a></td><td>X</td><td></td><td>7</td><td>2</td><td>5</td><td><b>7</b></td><td>0</td><td>0</td><td>0</td><td>5</td><td>12</td><td>29</td><td>12</td><td>19</td><td>6.90%</td><td>0</td><td>136</td><td>19.48</td><td>1</td><td>1</td><td>2</td><td>6</td><td>28</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>40</td><td><a href="PlayerReport.php?Player=102">Sidney Crosby (BUF)</a></td><td>X</td><td></td><td>8</td><td>2</td><td>5</td><td><b>7</b></td><td>2</td><td>2</td><td>0</td><td>9</td><td>14</td><td>26</td><td>10</td><td>23</td><td>7.69%</td><td>1</td><td>140</td><td>17.44</td><td>0</td><td>2</td><td>2</td><td>2</td><td>23</td><td>0</td><td>0</td><td>0</td><td>0</td><td>3</td></tr>
<tr><td>41</td><td><a href="PlayerReport.php?Player=87">Jon Marchessault (DAL)</a></td><td>X</td><td></td><td>9</td><td>2</td><td>5</td><td><b>7</b></td><td>1</td><td>8</td><td>0</td><td>20</td><td>14</td><td>38</td><td>14</td><td>17</td><td>5.26%</td><td>0</td><td>173</td><td>19.24</td><td>1</td><td>0</td><td>1</td><td>9</td><td>30</td><td>0</td><td>0</td><td>0</td><td>1</td><td>6</td></tr>
<tr><td>42</td><td><a href="PlayerReport.php?Player=246">Jamie Benn (WSH)</a></td><td>X</td><td></td><td>9</td><td>1</td><td>6</td><td><b>7</b></td><td>2</td><td>4</td><td>0</td><td>18</td><td>7</td><td>29</td><td>7</td><td>30</td><td>3.45%</td><td>3</td><td>181</td><td>20.08</td><td>0</td><td>3</td><td>3</td><td>5</td><td>27</td><td>0</td><td>0</td><td>0</td><td>0</td><td>6</td></tr>
<tr><td>43</td><td><a href="PlayerReport.php?Player=2196">Filip Forsberg (SJS)</a></td><td>X</td><td></td><td>7</td><td>5</td><td>1</td><td><b>6</b></td><td>4</td><td>4</td><td>0</td><td>23</td><td>14</td><td>23</td><td>8</td><td>22</td><td>21.74%</td><td>3</td><td>139</td><td>19.92</td><td>2</td><td>0</td><td>2</td><td>6</td><td>29</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>44</td><td><a href="PlayerReport.php?Player=154">Kasperi Kapanen (WPG)</a></td><td>X</td><td></td><td>9</td><td>5</td><td>1</td><td><b>6</b></td><td>6</td><td>0</td><td>0</td><td>13</td><td>8</td><td>27</td><td>6</td><td>22</td><td>18.52%</td><td>3</td><td>177</td><td>19.65</td><td>1</td><td>0</td><td>1</td><td>5</td><td>26</td><td>0</td><td>0</td><td>0</td><td>0</td><td>1</td></tr>
<tr><td>45</td><td><a href="PlayerReport.php?Player=453">Anthony Beauvillier (STL)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>2</td><td><b>6</b></td><td>2</td><td>0</td><td>0</td><td>8</td><td>11</td><td>24</td><td>5</td><td>12</td><td>16.67%</td><td>1</td><td>131</td><td>18.74</td><td>0</td><td>0</td><td>0</td><td>5</td><td>20</td><td>0</td><td>0</td><td>0</td><td>1</td><td>7</td></tr>
<tr><td>46</td><td><a href="PlayerReport.php?Player=1689">Sean Couturier (BOS)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>2</td><td><b>6</b></td><td>-2</td><td>0</td><td>0</td><td>3</td><td>24</td><td>32</td><td>8</td><td>23</td><td>12.50%</td><td>2</td><td>151</td><td>21.57</td><td>1</td><td>1</td><td>2</td><td>7</td><td>19</td><td>0</td><td>0</td><td>0</td><td>0</td><td>12</td></tr>
<tr><td>47</td><td><a href="PlayerReport.php?Player=2671">William Karlsson (NJD)</a></td><td>X</td><td></td><td>7</td><td>4</td><td>2</td><td><b>6</b></td><td>-1</td><td>0</td><td>0</td><td>4</td><td>18</td><td>14</td><td>7</td><td>8</td><td>28.57%</td><td>0</td><td>113</td><td>16.11</td><td>1</td><td>1</td><td>2</td><td>3</td><td>18</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>48</td><td><a href="PlayerReport.php?Player=536">Anze Kopitar (BUF)</a></td><td>X</td><td></td><td>8</td><td>4</td><td>2</td><td><b>6</b></td><td>3</td><td>2</td><td>0</td><td>5</td><td>28</td><td>34</td><td>4</td><td>17</td><td>11.76%</td><td>5</td><td>173</td><td>21.58</td><td>1</td><td>1</td><td>2</td><td>6</td><td>20</td><td>0</td><td>0</td><td>0</td><td>2</td><td>28</td></tr>
<tr><td>49</td><td><a href="PlayerReport.php?Player=1656">Craig Smith (VGK)</a></td><td>X</td><td></td><td>8</td><td>4</td><td>2</td><td><b>6</b></td><td>0</td><td>2</td><td>0</td><td>8</td><td>6</td><td>15</td><td>2</td><td>8</td><td>26.67%</td><td>1</td><td>116</td><td>14.54</td><td>1</td><td>1</td><td>2</td><td>3</td><td>20</td><td>0</td><td>0</td><td>0</td><td>0</td><td>0</td></tr>
<tr><td>50</td><td><a href="PlayerReport.php?Player=1729">Justin Faulk (CHI)</a></td><td></td><td>X</td><td>5</td><td>3</td><td>3</td><td><b>6</b></td><td>-1</td><td>0</td><td>0</td><td>12</td><td>6</td><td>16</td><td>2</td><td>3</td><td>18.75%</td><td>6</td><td>126</td><td>25.13</td><td>1</td><td>3</td><td>4</td><td>7</td><td>10</td><td>0</td><td>0</td><td>0</td><td>0</td><td>16</td></tr>
</table><table class="basictablesorter STHSScoring_GoaliesTable"><thead><tr><th class="STHSW25">#</th><th class="STHSW200">Goalie Name</th><th class="STHSW25">GP</th><th class="STHSW25">W</th><th class="STHSW25">L</th><th class="STHSW25">OTL</th><th class="STHSW50">PCT</th><th class="STHSW50">GAA</th><th class="STHSW50">MP</th><th class="STHSW25">PIM</th><th class="STHSW25">SO</th><th class="STHSW25">GA</th><th class="STHSW45">SA</th><th class="STHSW45">SAR</th><th class="STHSW25">A</th><th class="STHSW25">EG</th><th class="STHSW50">PS %</th><th class="STHSW25">PSA</th><th class="STHSW25">ST</th><th class="STHSW25">BG</th></tr></thead>
<tr><td>1</td><td><a href="GoalieReport.php?Goalie=59">Casey DeSmith (CGY)</a></td><td>4</td><td>4</td><td>0</td><td>0</td><td><b>0.966</b></td><td>1.00</td><td>240</td><td>0</td><td>1</td><td>4</td><td>116</td><td>0</td><td>0</td><td>0</td><td>0.000</td><td>0</td><td>4</td><td>4</td></tr>
<tr><td>2</td><td><a href="GoalieReport.php?Goalie=191">Philipp Grubauer (NYI)</a></td><td>5</td><td>4</td><td>0</td><td>0</td><td><b>0.955</b></td><td>1.21</td><td>247</td><td>0</td><td>1</td><td>5</td><td>110</td><td>0</td><td>0</td><td>0</td><td>0.000</td><td>0</td><td>5</td><td>0</td></tr>
<tr><td>3</td><td><a href="GoalieReport.php?Goalie=215">Darcy Kuemper (SJS)</a></td><td>7</td><td>5</td><td>1</td><td>1</td><td><b>0.940</b></td><td>1.84</td><td>425</td><td>0</td><td>0</td><td>13</td><td>215</td><td>0</td><td>0</td><td>0</td><td>0.667</td><td>3</td><td>7</td><td>0</td></tr>
<tr><td>4</td><td><a href="GoalieReport.php?Goalie=15">Andrei Vasilevskiy (OTT)</a></td><td>6</td><td>4</td><td>2</td><td>0</td><td><b>0.939</b></td><td>1.84</td><td>359</td><td>0</td><td>0</td><td>11</td><td>179</td><td>0</td><td>0</td><td>0</td><td>0.000</td><td>0</td><td>6</td><td>0</td></tr>
<tr><td>5</td><td><a href="GoalieReport.php?Goalie=169">Thomas Greiss (BUF)</a></td><td>8</td><td>4</td><td>2</td><td>2</td><td><b>0.933</b></td><td>1.87</td><td>481</td><td>0</td><td>0</td><td>15</td><td>223</td><td>0</td><td>1</td><td>0</td><td>0.000</td><td>0</td><td>8</td><td>0</td></tr>
<tr><td>6</td><td><a href="GoalieReport.php?Goalie=320">Matt Murray (WPG)</a></td><td>7</td><td>4</td><td>2</td><td>0</td><td><b>0.934</b></td><td>1.92</td><td>375</td><td>0</td><td>0</td><td>12</td><td>183</td><td>0</td><td>0</td><td>1</td><td>0.000</td><td>0</td><td>6</td><td>3</td></tr>
<tr><td>7</td><td><a href="GoalieReport.php?Goalie=93">Henrik Lundqvist (VAN)</a></td><td>6</td><td>6</td><td>0</td><td>0</td><td><b>0.936</b></td><td>1.95</td><td>370</td><td>0</td><td>1</td><td>12</td><td>187</td><td>0</td><td>0</td><td>0</td><td>0.800</td><td>5</td><td>6</td><td>0</td></tr>
<tr><td>8</td><td><a href="GoalieReport.php?Goalie=89">Pekka Rinne (CGY)</a></td><td>4</td><td>3</td><td>1</td><td>0</td><td><b>0.943</b></td><td>1.97</td><td>243</td><td>0</td><td>1</td><td>8</td><td>141</td><td>0</td><td>0</td><td>0</td><td>1.000</td><td>3</td><td>4</td><td>4</td></tr>
<tr><td>9</td><td><a href="GoalieReport.php?Goalie=51">Carey Price (NSH)</a></td><td>7</td><td>5</td><td>2</td><td>0</td><td><b>0.942</b></td><td>2.12</td><td>425</td><td>0</td><td>2</td><td>15</td><td>259</td><td>0</td><td>0</td><td>0</td><td>1.000</td><td>4</td><td>7</td><td>0</td></tr>
<tr><td>10</td><td><a href="GoalieReport.php?Goalie=92">Marc-Andre Fleury (NYR)</a></td><td>5</td><td>3</td><td>2</td><td>0</td><td><b>0.919</b></td><td>2.17</td><td>304</td><td>0</td><td>1</td><td>11</td><td>135</td><td>0</td><td>1</td><td>0</td><td>1.000</td><td>3</td><td>5</td><td>0</td></tr>
</table>
<?php include "Footer.php";?>
